-- EPIC-064A 후속: 관리자 로그인 시 '페이지 수정' 버튼이 뜨려면
-- page_builder에 해당 slug 행이 있어야 한다(PageEditButton이 이 행의
-- id로 /admin/pages/[id]를 링크한다). EPIC-064A는 컴포넌트만 심고 DB는
-- 건드리지 않았는데(지시 사항), 그 결과 9개 Hub(treasures/docent/heritage/
-- community/membership/gallery/archive/studio/mypage)에만 버튼이 보이고
-- 나머지 117개 하위 Route는 버튼이 안 보이는 문제가 발견됐다 — 이 파일로
-- 그 117개 행을 전부 draft로 만들어 버튼이 뜨게 한다.
--
-- status='draft'라 공개 페이지 화면에는 전혀 영향이 없다(admin만 볼 수
-- 있음, RLS: page_builder_public_read 정책 참고) — 대부분의 이 페이지들은
-- 애초에 page_builder를 읽지 않는 기존 코드(하드코딩 렌더링)라서, 이 행을
-- 만들어도 실제 화면 내용은 바뀌지 않고 '페이지 수정' 버튼만 뜬다. 버튼을
-- 눌러 /admin/pages에서 모듈을 구성해도 그 페이지가 page_builder를 직접
-- 읽지 않는 한(PageBuilderRenderer를 쓰는 페이지만 해당) 화면에 반영되지
-- 않는다 — 이 SQL은 '버튼이 보이게' 하는 것까지만 해결한다.
--
-- ON CONFLICT (slug) DO NOTHING이라 여러 번 실행해도 안전(멱등).

insert into page_builder (slug, title, status) values
  ('archive-brochure', 'Archive Brochure', 'draft'),
  ('archive-posters', 'Archive Posters', 'draft'),
  ('archive-timeline', 'Archive Timeline', 'draft'),
  ('attendance', 'Attendance', 'draft'),
  ('boards', 'Boards', 'draft'),
  ('boards-id', 'Boards Id', 'draft'),
  ('boards-id-postid', 'Boards Id Postid', 'draft'),
  ('boards-id-write', 'Boards Id Write', 'draft'),
  ('clubs', 'Clubs', 'draft'),
  ('clubs-id', 'Clubs Id', 'draft'),
  ('community-club-name', 'Community Club Name', 'draft'),
  ('community-events', 'Community Events', 'draft'),
  ('community-general', 'Community General', 'draft'),
  ('community-qna', 'Community Qna', 'draft'),
  ('community-topics', 'Community Topics', 'draft'),
  ('community-topics-art', 'Community Topics Art', 'draft'),
  ('community-topics-comedy', 'Community Topics Comedy', 'draft'),
  ('community-topics-economy', 'Community Topics Economy', 'draft'),
  ('community-topics-health', 'Community Topics Health', 'draft'),
  ('community-topics-literature', 'Community Topics Literature', 'draft'),
  ('community-topics-movie', 'Community Topics Movie', 'draft'),
  ('community-topics-pet-owners', 'Community Topics Pet Owners', 'draft'),
  ('community-topics-politics', 'Community Topics Politics', 'draft'),
  ('community-topics-psychology', 'Community Topics Psychology', 'draft'),
  ('community-topics-science', 'Community Topics Science', 'draft'),
  ('community-topics-sports', 'Community Topics Sports', 'draft'),
  ('community-topics-warm-world', 'Community Topics Warm World', 'draft'),
  ('community-topics-world-history', 'Community Topics World History', 'draft'),
  ('community-weekday', 'Community Weekday', 'draft'),
  ('community-weekday-after-the-play', 'Community Weekday After The Play', 'draft'),
  ('community-weekday-anything-can-happen', 'Community Weekday Anything Can Happen', 'draft'),
  ('community-weekday-before-sunrise', 'Community Weekday Before Sunrise', 'draft'),
  ('community-weekday-between-lines', 'Community Weekday Between Lines', 'draft'),
  ('community-weekday-book', 'Community Weekday Book', 'draft'),
  ('community-weekday-english-play', 'Community Weekday English Play', 'draft'),
  ('community-weekday-monday', 'Community Weekday Monday', 'draft'),
  ('docent-art-deco', 'Docent Art Deco', 'draft'),
  ('docent-art-nouveau', 'Docent Art Nouveau', 'draft'),
  ('docent-baroque', 'Docent Baroque', 'draft'),
  ('docent-beat-generation', 'Docent Beat Generation', 'draft'),
  ('docent-collections', 'Docent Collections', 'draft'),
  ('docent-counterculture', 'Docent Counterculture', 'draft'),
  ('docent-digital', 'Docent Digital', 'draft'),
  ('docent-id', 'Docent Id', 'draft'),
  ('docent-library', 'Docent Library', 'draft'),
  ('docent-neoclassicism', 'Docent Neoclassicism', 'draft'),
  ('docent-regency', 'Docent Regency', 'draft'),
  ('docent-renaissance', 'Docent Renaissance', 'draft'),
  ('docent-rococo', 'Docent Rococo', 'draft'),
  ('docent-victoria', 'Docent Victoria', 'draft'),
  ('downloads', 'Downloads', 'draft'),
  ('event-notices', 'Event Notices', 'draft'),
  ('gallery-awards', 'Gallery Awards', 'draft'),
  ('gallery-parties', 'Gallery Parties', 'draft'),
  ('gallery-patrons', 'Gallery Patrons', 'draft'),
  ('gallery-performance', 'Gallery Performance', 'draft'),
  ('gallery-visitors', 'Gallery Visitors', 'draft'),
  ('heritage-grandma-name', 'Heritage Grandma Name', 'draft'),
  ('heritage-grandmas', 'Heritage Grandmas', 'draft'),
  ('heritage-grandpa-name', 'Heritage Grandpa Name', 'draft'),
  ('heritage-grandpas', 'Heritage Grandpas', 'draft'),
  ('home', 'Home', 'draft'),
  ('login', 'Login', 'draft'),
  ('me', 'Me', 'draft'),
  ('me-write', 'Me Write', 'draft'),
  ('membership-artist-intro', 'Membership Artist Intro', 'draft'),
  ('membership-mind-diary', 'Membership Mind Diary', 'draft'),
  ('membership-my-treasures', 'Membership My Treasures', 'draft'),
  ('membership-one-sentence-novel', 'Membership One Sentence Novel', 'draft'),
  ('membership-patron', 'Membership Patron', 'draft'),
  ('membership-secret-room', 'Membership Secret Room', 'draft'),
  ('monthly-events', 'Monthly Events', 'draft'),
  ('mypage-badges', 'Mypage Badges', 'draft'),
  ('mypage-bucketlist', 'Mypage Bucketlist', 'draft'),
  ('mypage-collections', 'Mypage Collections', 'draft'),
  ('mypage-collections-category', 'Mypage Collections Category', 'draft'),
  ('mypage-comments', 'Mypage Comments', 'draft'),
  ('mypage-docent-certificate', 'Mypage Docent Certificate', 'draft'),
  ('mypage-exhibition', 'Mypage Exhibition', 'draft'),
  ('mypage-follow', 'Mypage Follow', 'draft'),
  ('mypage-salon', 'Mypage Salon', 'draft'),
  ('mypage-space', 'Mypage Space', 'draft'),
  ('mypage-timeline', 'Mypage Timeline', 'draft'),
  ('mypage-visitors', 'Mypage Visitors', 'draft'),
  ('mypage-wishlist', 'Mypage Wishlist', 'draft'),
  ('polls', 'Polls', 'draft'),
  ('rental', 'Rental', 'draft'),
  ('rental-rentaltypeid', 'Rental Rentaltypeid', 'draft'),
  ('salon-artist-intro', 'Salon Artist Intro', 'draft'),
  ('salon-checkin', 'Salon Checkin', 'draft'),
  ('salon-docent-tour', 'Salon Docent Tour', 'draft'),
  ('salon-drinks', 'Salon Drinks', 'draft'),
  ('salon-gallery-awards', 'Salon Gallery Awards', 'draft'),
  ('salon-gallery-parties', 'Salon Gallery Parties', 'draft'),
  ('salon-gallery-patrons', 'Salon Gallery Patrons', 'draft'),
  ('salon-gallery-performances', 'Salon Gallery Performances', 'draft'),
  ('salon-gallery-visitors', 'Salon Gallery Visitors', 'draft'),
  ('salon-mind-diary', 'Salon Mind Diary', 'draft'),
  ('salon-my-treasure-story', 'Salon My Treasure Story', 'draft'),
  ('salon-one-sentence-novel', 'Salon One Sentence Novel', 'draft'),
  ('salon-secret-room', 'Salon Secret Room', 'draft'),
  ('settings', 'Settings', 'draft'),
  ('shop', 'Shop', 'draft'),
  ('shop-heritage-grandma', 'Shop Heritage Grandma', 'draft'),
  ('shop-heritage-grandpa', 'Shop Heritage Grandpa', 'draft'),
  ('shop-id', 'Shop Id', 'draft'),
  ('shop-projects', 'Shop Projects', 'draft'),
  ('shop-projects-id', 'Shop Projects Id', 'draft'),
  ('shop-reviews', 'Shop Reviews', 'draft'),
  ('signup', 'Signup', 'draft'),
  ('space-inquiry-item-rental', 'Space Inquiry Item Rental', 'draft'),
  ('space-inquiry-shoot-rental', 'Space Inquiry Shoot Rental', 'draft'),
  ('space-inquiry-styling', 'Space Inquiry Styling', 'draft'),
  ('studio-items', 'Studio Items', 'draft'),
  ('studio-rental', 'Studio Rental', 'draft'),
  ('studio-styling', 'Studio Styling', 'draft'),
  ('u-memberid', 'U Memberid', 'draft')
on conflict (slug) do nothing;
