-- EPIC-165: /membership — 문 로비(기존 '혜택의 문' 대체)와 스킬 트리 위젯. 재실행 안전.
update page_modules set settings = $j${"heading":"사일로의 문을 열어보세요","subtitle":"문을 눌러 안으로 들어가 보세요","doors":[{"imageUrl":"","title":"About Silo","tagline":"에단과 수미의 일상과 취향 로그","description":"사일로의 주인 '에단과 수미'의 일상과 취향 로그.\n오래 모아 온 것들과 그 이야기를 가장 먼저 만나는 문이에요.","extra":"사일로 타임라인 · 사일로의 하루 등\n게시판 3개가 이 문 안에 있어요.","href":"/about-silo","hrefLabel":"About Silo 들어가기","accent":"#E4C84B"},{"imageUrl":"","title":"사일로 상점","tagline":"오래된 보물이 새 주인을 찾는 과정","description":"사일로의 오래된 보물이 새로운 주인을 찾아가는 모든 과정.\n고르고, 사연을 듣고, 집으로 데려가는 여정을 함께해요.","extra":"","href":"/shop","hrefLabel":"상점 둘러보기","accent":"#C9A46A"},{"imageUrl":"","title":"살롱데상","tagline":"'백명의 전시회' — 영감·창작·공유","description":"'백명의 전시회'라는 이름처럼,\n영감, 창작, 공유하는 우리 이야기.","extra":"","href":"/clubs","hrefLabel":"살롱데상 만나기","accent":"#F28C28"},{"imageUrl":"","title":"온라인 도슨트","tagline":"그 기록으로 오늘을 비춰보기","description":"과거를 바꿀 순 없지만,\n그 기록으로 영감을 얻어 오늘을 비춰보기.","extra":"","href":"/docent","hrefLabel":"도슨트 듣기","accent":"#2ECC8F"},{"imageUrl":"","title":"스튜디오","tagline":"공간 대여 · 서로의 감성으로 찍은 사진","description":"사일로 & 살롱데상 공간 대여,\n서로의 감성으로 찍은 사진 공유.","extra":"","href":"/studio","hrefLabel":"스튜디오 보기","accent":"#9FC1FF"},{"imageUrl":"","title":"Silo Planet","tagline":"어린왕자의 행성처럼, 나만의 행성","description":"'어린왕자'의 행성처럼,\n나만의 행성을 꾸미고 다른 행성과 연결하기.","extra":"","href":"/silo-planet","hrefLabel":"행성으로 떠나기","accent":"#8E5BD1"},{"imageUrl":"","title":"마이페이지","tagline":"'내가 선택한 나'를 아카이빙","description":"'내가 선택한 나'를 아카이빙 하기.\n팔로우로 연결된 너와 나.","extra":"","href":"/mypage","hrefLabel":"내 공간으로","accent":"#E2412F"}]}$j$::jsonb
where module_type = 'membership_doors' and page_id = (select id from page_builder where slug = 'membership')
  and not exists (select 1 from jsonb_array_elements(coalesce(settings->'doors','[]'::jsonb)) d where d ? 'description');
update page_modules set sort_order = sort_order + 1
where page_id = (select id from page_builder where slug = 'membership') and sort_order >= 4
  and not exists (select 1 from page_modules where module_type = 'membership_skilltree' and page_id = (select id from page_builder where slug = 'membership'));
insert into page_modules (page_id, module_type, sort_order, settings)
select (select id from page_builder where slug = 'membership'), 'membership_skilltree', 4, $j${"heading":"등급이 오를수록 열리는 문","subtitle":"Silo Angel에서 시작해 한 걸음씩, 새 가지가 열려요","branches":[{"rank":0,"icon":"🏠","title":"마이페이지","desc":"'내가 선택한 나'를 기록해요. 글은 총 5개까지."},{"rank":0,"icon":"🪐","title":"사일로 플래닛","desc":"내 행성과 사일로 행성 두 곳을 둘러봐요."},{"rank":0,"icon":"🍷","title":"온라인 도슨트 맛보기","desc":"첫인사 글을 열람해요."},{"rank":1,"icon":"✍️","title":"글쓰기 제한 해제","desc":"5개 제한 없이 자유롭게 기록해요."},{"rank":1,"icon":"🔭","title":"다른 회원의 행성","desc":"다른 회원의 행성을 구경하고 좋아요를 눌러요."},{"rank":1,"icon":"🤝","title":"클럽 모임","desc":"모임에 참여하고 10% 할인을 받아요."},{"rank":2,"icon":"🔑","title":"도슨트 하루 1편","desc":"온라인 도슨트를 하루 한 편 열어 봐요."},{"rank":2,"icon":"🥂","title":"파티 우선 예매","desc":"살롱데상 파티를 먼저 예매해요."},{"rank":3,"icon":"💎","title":"내 행성 꾸미기(3D)","desc":"나만의 3D 행성 에셋을 올려 꾸며요."},{"rank":3,"icon":"💌","title":"은밀한 사연","desc":"물건의 이전 주인이 남긴 사연을 읽어요."},{"rank":3,"icon":"👑","title":"살롱 상시 출입","desc":"살롱데상에 자유롭게 드나들어요."},{"rank":4,"icon":"🖋️","title":"살롱의 목소리(칼럼)","desc":"칼럼을 쓰고 목소리를 남겨요."},{"rank":4,"icon":"🎭","title":"전시·공연 기획","desc":"전시와 공연을 직접 기획하고 주최해요."},{"rank":4,"icon":"🏅","title":"생태계 제안·추천권","desc":"행성과 사일로의 다음 모습을 제안해요."},{"rank":99,"icon":"🎨","title":"초대받는 자리","desc":"무대와 전시로 사일로를 채워 준 예술가를 위한 자리예요."}]}$j$::jsonb
where not exists (select 1 from page_modules where module_type = 'membership_skilltree' and page_id = (select id from page_builder where slug = 'membership'));
